Increase stack size for PowerShell 5 (#1797)
Sets the `Thread` max stack size to use the same value that is normally used in console host. This gives PowerShell code more room for execution, so recursive calls, or calls that are wrapped in Pester (which itself is stack-hungry), won't fail with: 

```
System.Management.Automation.ScriptCallDepthException: The script failed due to call depth overflow.
```

Fixes: https://github.com/PowerShell/vscode-powershell/issues/3962